export const SET_TOURNAMENTS = 'SET_TOURNAMENTS';
export const SET_TOURNAMENT_ID = 'SET_TOURNAMENT_ID';
export const SET_CURRENT_TOURNAMENT = 'SET_CURRENT_TOURNAMENT';
export const SET_CREATED_TOURNAMENT = 'SET_CREATED_TOURNAMENT';

export const SET_CURRENT_ROUND = 'SET_CURRENT_ROUND';
export const SET_ROUND_AND_FIXTURES = 'SET_ROUND_AND_FIXTURES';
export const SET_ALL_MATCHES_EXISTS = 'SET_ALL_MATCHES_EXISTS';
export const SET_UNHANDLED_MATCHES = 'SET_UNHANDLED_MATCHES';
export const SET_USERS = 'SET_USERS';
export const GET_MATCHES = 'GET_MATCHES';
export const SET_MATCHES = 'SET_MATCHES';
