export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT';
export const SET_TOURNAMENTS = 'SET_TOURNAMENTS';
export const GET_TOURNAMENT = 'GET_TOURNAMENT';
export const CREATE_MODE_RESET = 'CREATE_MODE_RESET';
export const SET_TOURNAMENT_ID = 'SET_TOURNAMENT_ID';
export const SET_CURRENT_TOURNAMENT = 'SET_CURRENT_TOURNAMENT';
export const SET_CREATED_TOURNAMENT = 'SET_CREATED_TOURNAMENT';

export const GET_MATCHES = 'GET_MATCHES';
export const SET_MATCHES = 'SET_MATCHES';
